const products = [
  {
    name: "Unisex Granny Square Shrit",
    description:
      "Unisex Granny Square Shirt. Note: Only S size is available and ready to ship. Other sizes are customizable and will take extra time to prepare.",
    price: 2000,
    ratings: 0,
    image: [
      {
        public_id: "Unisex_Granny_Square_Shrit_1",
        url: "https://dummyimage.com/600x400/blue/fff&text=Unisex+Shirt",
      },
    ],
    category: "Men",
    subcategory: "Shirt",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Unisex Granny Square Polo T-Shrit",
    description:
      "Unisex Granny Square Shirt. Note: Only S size is available and ready to ship. Other sizes are customizable and will take extra time to prepare.",
    price: 2000,
    ratings: 0,
    image: [
      {
        public_id: "Unisex_Granny_Square_Polo_T_Shrit_2",
        url: "https://dummyimage.com/600x400/yellow/fff&text=Polo+Tshirt",
      },
    ],
    category: "Men",
    subcategory: "T-Shirt",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Top",
    description:
      "half sleeves PimPom Top, round heck . Note: Only S size is available and ready to ship. Other sizes are customizable and will take extra time to prepare.",
    price: 650,
    ratings: 0,
    image: [
      {
        public_id: "Womens_Top_3",
        url: "https://dummyimage.com/600x400/lilac/fff&text=Women+Top",
      },
    ],
    category: "Women",
    subcategory: "Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Polo Neck Women's Crop Top ",
    description:
      "Sleeves less Collored Polo heck top. Note: Only S size is available and ready to ship. Other sizes are customizable and will take extra time to prepare.",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Polo_Neck_Womens_Crop_Top_4",
        url: "https://dummyimage.com/600x400/pink/fff&text=Polo+Neck+Top",
      },
    ],
    category: "Women",
    subcategory: "Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Unisex Granny Square Shrit",
    description:
      "Unisex Granny Square Shrit. Note: Only S size is available and ready to ship. Other sizes are customizable and will take extra time to prepare.",
    price: 900,
    ratings: 0,
    image: [
      {
        public_id: "Unisex_Granny_Square_Shrit_5",
        url: "https://dummyimage.com/600x400/white/222&text=Granny+Crop",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Mesh net Women's Crop Top ",
    description:
      "mesh net crop top with sleeves. Note: Only S size is available and ready to ship. Other sizes are customizable and will take extra time to prepare.",
    price: 700,
    ratings: 0,
    image: [
      {
        public_id: "Mesh_net_Womens_Crop_Top_6",
        url: "https://dummyimage.com/600x400/pink/fff&text=Mesh+Crop",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Crop Top ",
    description:
      "Vneck, with half sleeves. Note: Only S size is available and ready to ship. Other sizes are customizable and will take extra time to prepare.",
    price: 1500,
    ratings: 0,
    image: [
      {
        public_id: "Women_Crop_Top_7",
        url: "https://dummyimage.com/600x400/babypink/fff&text=Vneck+Crop",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Crop Top ",
    description: "Lace Top",
    price: 1000,
    ratings: 0,
    image: [
      {
        public_id: "Women_Crop_Top_8",
        url: "https://dummyimage.com/600x400/pink/fff&text=Lace+Crop",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Crop Top ",
    description: "Tank Top ",
    price: 700,
    ratings: 0,
    image: [
      {
        public_id: "Women_Crop_Top_9",
        url: "https://dummyimage.com/600x400/brown/fff&text=Tank+Crop",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Shrug",
    description: "Front Tie Ribbedcrop Cardigan  ",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Women_Shrug_10",
        url: "https://dummyimage.com/600x400/lilac/fff&text=Shrug",
      },
    ],
    category: "Women",
    subcategory: "Shrug",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Mesh net Women's Shrug",
    description: "Front Tie mesh net west  ",
    price: 500,
    ratings: 0,
    image: [
      {
        public_id: "Mesh_net_Womens_Shrug_11",
        url: "https://dummyimage.com/600x400/red/000&text=Mesh+Shrug",
      },
    ],
    category: "Women",
    subcategory: "Shrug",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Shrug",
    description: "Bolero Shrug",
    price: 500,
    ratings: 0,
    image: [
      {
        public_id: "Women_Shrug_12",
        url: "https://dummyimage.com/600x400/grey/fff&text=Bolero+Shrug",
      },
    ],
    category: "Women",
    subcategory: "Shrug",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Shrug",
    description: "West Top",
    price: 900,
    ratings: 0,
    image: [
      {
        public_id: "Women_Shrug_13",
        url: "https://dummyimage.com/600x400/olivegreen/violet&text=West+Top",
      },
    ],
    category: "Women",
    subcategory: "Shrug",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's TankTop ",
    description: "Floral lace tank top",
    price: 450,
    ratings: 0,
    image: [
      {
        public_id: "Women_TankTop_14",
        url: "https://dummyimage.com/600x400/brown/fff&text=Floral+Tank",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Women's Tank Top",
    description: "Summer May Tank Top",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Women_Tank_Top_15",
        url: "https://dummyimage.com/600x400/grey/fff&text=Summer+Tank",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Disstressed Women's Crop Top",
    description: "Disstressed crop Top",
    price: 450,
    ratings: 0,
    image: [
      {
        public_id: "Disstressed_Womens_Crop_Top_16",
        url: "https://dummyimage.com/600x400/red/fff&text=Distress+Crop",
      },
    ],
    category: "Women",
    subcategory: "Crop Top",
    stock: 5,
    size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Born Baby Frock",
    description: "Born Baby Frock",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Born_Baby_Frock_17",
        url: "https://dummyimage.com/600x400/pink/fff&text=Baby+Frock",
      },
    ],
    category: "Kids",
    subcategory: "Girl Baby",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Born Baby Frock",
    description: "Born Baby Frock",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Born_Baby_Frock_18",
        url: "https://dummyimage.com/600x400/violet/fff&text=Baby+Frock",
      },
    ],
    category: "Kids",
    subcategory: "Girl Baby",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Born Baby Frock",
    description: "Born Baby Frock",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Born_Baby_Frock_19",
        url: "https://dummyimage.com/600x400/red/fff&text=Baby+Frock",
      },
    ],
    category: "Kids",
    subcategory: "Girl Baby",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Born Baby Frock full set",
    description: "Born Baby Frock full set",
    price: 1500,
    ratings: 0,
    image: [
      {
        public_id: "Born_Baby_Frock_full_set_20",
        url: "https://dummyimage.com/600x400/orange/fff&text=Baby+Set",
      },
    ],
    category: "Kids",
    subcategory: "Girl Baby",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Born Baby Frock",
    description: "Born Baby Frock",
    price: 400,
    ratings: 0,
    image: [
      {
        public_id: "Born_Baby_Frock_21",
        url: "https://dummyimage.com/600x400/olive/fff&text=Baby+Frock",
      },
    ],
    category: "Kids",
    subcategory: "Girl Baby",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Beanie",
    description: "Round light sandal colour beanie",
    price: 300,
    ratings: 0,
    image: [
      {
        public_id: "Beanie_Accessories_22",
        url: "https://dummyimage.com/600x400/sand/fff&text=Beanie",
      },
    ],
    category: "Accessories",
    subcategory: "Beanie",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Beanie",
    description: "Round light sandal colour beanie with stripes",
    price: 300,
    ratings: 0,
    image: [
      {
        public_id: "Beanie_Accessories_23",
        url: "https://dummyimage.com/600x400/sand/000&text=Striped+Beanie",
      },
    ],
    category: "Accessories",
    subcategory: "Beanie",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Beanie",
    description: "Multi colour slouchy",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Beanie_Accessories_24",
        url: "https://dummyimage.com/600x400/multi/fff&text=Slouchy+Beanie",
      },
    ],
    category: "Accessories",
    subcategory: "Beanie",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Beanie",
    description: "Rabit beanie",
    price: 500,
    ratings: 0,
    image: [
      {
        public_id: "Beanie_Accessories_25",
        url: "https://dummyimage.com/600x400/violet/fff&text=Rabit+Beanie",
      },
    ],
    category: "Accessories",
    subcategory: "Beanie",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Beanie",
    description: "round beanie",
    price: 400,
    ratings: 0,
    image: [
      {
        public_id: "Beanie_Accessories_26",
        url: "https://dummyimage.com/600x400/violet/fff&text=Round+Beanie",
      },
    ],
    category: "Accessories",
    subcategory: "Beanie",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Beanie",
    description: "Riped Slouchy",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Beanie_Accessories_27",
        url: "https://dummyimage.com/600x400/grey/000&text=Ripped+Slouchy",
      },
    ],
    category: "Accessories",
    subcategory: "Beanie",
    stock: 5,
    size: ["Available in all sizes"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },

  {
    name: "Scarf",
    description: "dimensions -5 inch * 60 inch",
    price: 350,
    ratings: 0,
    image: [
      {
        public_id: "Scarf_Accessories_28",
        url: "https://dummyimage.com/600x400/maroon/fff&text=Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Ziczac Knitted Scarf",
    description: "Ziczac Knitted Scarf, dimensions - 6.5 inch * 83 inch",
    price: 1700,
    ratings: 0,
    image: [
      {
        public_id: "Ziczac_Knitted_Scarf_29",
        url: "https://dummyimage.com/600x400/darkviolet/fff&text=Ziczac+Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Classic Chevron Ridge Scarf",
    description: "dimensions -6.5 inch * 82 inch",
    price: 1500,
    ratings: 0,
    image: [
      {
        public_id: "Classic_Chevron_Ridge_Scarf_30",
        url: "https://dummyimage.com/600x400/pink/fff&text=Chevron+Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Triangle prayer shawel",
    description: "",
    price: 1000,
    ratings: 0,
    image: [
      {
        public_id: "Triangle_prayer_shawel_31",
        url: "https://dummyimage.com/600x400/blue/fff&text=Prayer+Shawel",
      },
    ],
    category: "Accessories",
    subcategory: "Shawel",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Checkered Scarf",
    description: "Checkered Scarf with twisted fringes",
    price: 1500,
    ratings: 0,
    image: [
      {
        public_id: "Checkered_Scarf_32",
        url: "https://dummyimage.com/600x400/snadalgray/000&text=Checkered+Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "hoodie Scarf",
    description: "hoodie Scarf",
    price: 1500,
    ratings: 0,
    image: [
      {
        public_id: "Hoodie_Scarf_33",
        url: "https://dummyimage.com/600x400/lightgrey/000&text=Hoodie+Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Eyelet Scarf",
    description: "Eyelet Scarf, dimensions- 7inch * 65 inch",
    price: 1200,
    ratings: 0,
    image: [
      {
        public_id: "Eyelet_Scarf_34",
        url: "https://dummyimage.com/600x400/blue/fff&text=Eyelet+Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Knitted Scarf",
    description: "Green Knitted Scarf",
    price: 600,
    ratings: 0,
    image: [
      {
        public_id: "Knitted_Scarf_35",
        url: "https://dummyimage.com/600x400/lightgreen/fff&text=Knitted+Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Granny Square Scarf",
    description: "Blue Granny Square Scarf with beads fringes",
    price: 1800,
    ratings: 0,
    image: [
      {
        public_id: "Granny_Square_Scarf_36",
        url: "https://dummyimage.com/600x400/blue/fff&text=Granny+Scarf",
      },
    ],
    category: "Accessories",
    subcategory: "Scarf",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },

  // --- Table Decor ---
  {
    name: "Table Runner",
    description: "Black Musted table Runner, dimensions- 9inch * 29inch",
    price: 300,
    ratings: 0,
    image: [
      {
        public_id: "Table_Runner_37",
        url: "https://dummyimage.com/600x400/black/ddd&text=Table+Runner",
      },
    ],
    category: "TableDecor",
    subcategory: "Table Runner",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Doily Coaster",
    description: "Doily Coaster",
    price: 100,
    ratings: 0,
    image: [
      {
        public_id: "Doily_Coaster_38",
        url: "https://dummyimage.com/600x400/lightgrey/000&text=Doily+Coaster",
      },
    ],
    category: "TableDecor",
    subcategory: "Tea Coaster",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Spiral Coaster",
    description: "Spiral Coaster",
    price: 100,
    ratings: 0,
    image: [
      {
        public_id: "Spiral_Coaster_39",
        url: "https://dummyimage.com/600x400/red/fff&text=Spiral+Coaster",
      },
    ],
    category: "TableDecor",
    subcategory: "Tea Coaster",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Square Coaster",
    description: "Square Coaster",
    price: 100,
    ratings: 0,
    image: [
      {
        public_id: "Square_Coaster_40",
        url: "https://dummyimage.com/600x400/brown/fff&text=Square+Coaster",
      },
    ],
    category: "TableDecor",
    subcategory: "Tea Coaster",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },

  // --- KeyChains ---
  {
    name: "Baby Whale Amigururmi",
    description: "Baby Whale Amigururmi",
    price: 150,
    ratings: 0,
    image: [
      {
        public_id: "Baby_Whale_Amigururmi_41",
        url: "https://dummyimage.com/600x400/multi/000&text=Whale+Keychain",
      },
    ],
    category: "Accessories",
    subcategory: "KeyChains",
    stock: 5,
    size: ["Medium"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Heart Keychains",
    description: "Heart Keychains",
    price: 100,
    ratings: 0,
    image: [
      {
        public_id: "Heart_Keychains_42",
        url: "https://dummyimage.com/600x400/multi/fff&text=Heart+Keychain",
      },
    ],
    category: "Accessories",
    subcategory: "KeyChains",
    stock: 5,
    size: ["Medium"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Flower Keychains",
    description: "Flower Keychains",
    price: 70,
    ratings: 0,
    image: [
      {
        public_id: "Flower_Keychains_43",
        url: "https://dummyimage.com/600x400/multi/fff&text=Flower+Keychain",
      },
    ],
    category: "Accessories",
    subcategory: "KeyChains",
    stock: 5,
    size: ["Medium"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Fish Keychains",
    description: "Fish Keychains Single colour",
    price: 50,
    ratings: 0,
    image: [
      {
        public_id: "Fish_Keychains_Single_44",
        url: "https://dummyimage.com/600x400/blue/fff&text=Fish+Keychain+1",
      },
    ],
    category: "Accessories",
    subcategory: "KeyChains",
    stock: 5,
    size: ["Medium"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Fish Keychains",
    description: "Fish Keychains Double colour",
    price: 50,
    ratings: 0,
    image: [
      {
        public_id: "Fish_Keychains_Double_45",
        url: "https://dummyimage.com/600x400/multi/fff&text=Fish+Keychain+2",
      },
    ],
    category: "Accessories",
    subcategory: "KeyChains",
    stock: 5,
    size: ["Medium"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Butterfly Keychains",
    description: "Butterfly Keychains",
    price: 75,
    ratings: 0,
    image: [
      {
        public_id: "Butterfly_Keychains_46",
        url: "https://dummyimage.com/600x400/multi/000&text=Butterfly+Keychain",
      },
    ],
    category: "Accessories",
    subcategory: "KeyChains",
    stock: 5,
    size: ["Medium"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },

  // --- Scrunchies ---
  {
    name: "Scrunchies",
    description: "Scrunchies Single colour",
    price: 40,
    ratings: 0,
    image: [
      {
        public_id: "Scrunchies_Single_47",
        url: "https://dummyimage.com/600x400/multi/fff&text=Scrunchie+Single",
      },
    ],
    category: "Accessories",
    subcategory: "Scrunchies",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Scrunchies",
    description: "Scrunchies Multi-colour",
    price: 50,
    ratings: 0,
    image: [
      {
        public_id: "Scrunchies_Multi_48",
        url: "https://dummyimage.com/600x400/multi/000&text=Scrunchie+Multi",
      },
    ],
    category: "Accessories",
    subcategory: "Scrunchies",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },

  // --- Hairclips ---
  {
    name: "Hairclips",
    description: "Hairclips",
    price: 30,
    ratings: 0,
    image: [
      {
        public_id: "Hairclips_49",
        url: "https://dummyimage.com/600x400/multi/000&text=Hairclip",
      },
    ],
    category: "Accessories",
    subcategory: "Hairclips",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },

  // --- Bags ---
  {
    name: "T-Shirt Yarn Bags",
    description: "T-Shirt Yarn Bags",
    price: 200,
    ratings: 0,
    image: [
      {
        public_id: "TShirt_Yarn_Bags_50",
        url: "https://dummyimage.com/600x400/brown/fff&text=Yarn+Bag",
      },
    ],
    category: "Bags",
    subcategory: "Slig Bags",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Sling bag",
    description: "Sling bag",
    price: 500,
    ratings: 0,
    image: [
      {
        public_id: "Sling_Bag_Green_51",
        url: "https://dummyimage.com/600x400/green/fff&text=Sling+Bag",
      },
    ],
    category: "Bags",
    subcategory: "Sling Bags",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Sling bag",
    description: "Sling bag",
    price: 500,
    ratings: 0,
    image: [
      {
        public_id: "Sling_Bag_Yellow_52",
        url: "https://dummyimage.com/600x400/yellow/000&text=Sling+Bag",
      },
    ],
    category: "Bags",
    subcategory: "Sling Bags",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Sling Phone bag",
    description: "Sling bag",
    price: 200,
    ratings: 0,
    image: [
      {
        public_id: "Sling_Phone_Bag_53",
        url: "https://dummyimage.com/600x400/goldenbrown/fff&text=Phone+Bag",
      },
    ],
    category: "Bags",
    subcategory: "Sling phone Bags",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
  {
    name: "Sling bag",
    description: "Sling bag",
    price: 700,
    ratings: 0,
    image: [
      {
        public_id: "Sling_Bag_Yellow_Variegated_54",
        url: "https://dummyimage.com/600x400/yellow/000&text=Variegated+Sling",
      },
    ],
    category: "Bags",
    subcategory: "Sling Bags",
    stock: 5,
    size: ["One size"],
    numberOfReviews: 0,
    reviews: [],
    user: "userObjectId",
    createdAt: new Date(),
  },
];

export default products;
